### ISSUE TITLE
PREP_SYSTEM_FOR_DIETPI.sh fails because https is enabled in sources.list

### ISSUE THREAD

**Issue by optio50** [MichaIng/DietPi#2257]
PREP_SYSTEM_FOR_DIETPI.sh
Method https has died unexpectedly
fails because sources.list https is enabled before during and after install of DietPi
Hardware is Odroid U3 with https://oph.mdrjr.net/meveric/images/Jessie/Debian-Jessie-1.1-20170515-U.img.xz
Debian Jessie & DietPi upgrades to Stretch
Kernel 3.8.13.30

I was able to complete the install by simultaneously starting another login and modifying the /etc/apt/sources.list while the script was running.

**Comment by MichaIng** [comment]
@optio50 
Thanks for your report.

Ahh I remember seeing this error some time ago, but cannot find related issue or remember how we solved it.

- Can you paste the related part of the terminal output, to let us see on which APT call this happened?
- Can you verify `apt-transport-https` and `ca-certificates` packages are installed: `dpkg-query -s apt-transport-https ca-certificates`

> fails because sources.list https is enabled before during and after install of DietPi

So this error appears before even running DietPi-PREP script? Test on fresh Meveric image and then: `apt update && apt full-upgrade`

> I was able to complete the install by simultaneously starting another login and modifying the /etc/apt/sources.list while the script was running.

Jep, best solution/attempt whenever a DietPi scripts throws an error and prompts a whiptail menu, since you can mostly choose "retry".

But in this case would be good to find the reason, since we want APT to use `https` whenever available for security and privacy reasons. With `apt-transport-https` and `ca-certificates` packages this should generally work.

Is it actually possible now, with DietPi being successfully installed, to re-enable https within `sources.list`?

**Comment by Fourdee** [comment]
Strange, Jessie is set to http in DietPi code:
- https://github.com/Fourdee/DietPi/blob/master/dietpi/func/dietpi-set_software#L158-L167

Apt mirror applied before any ```G_AG``` commands
- https://github.com/Fourdee/DietPi/blob/master/PREP_SYSTEM_FOR_DIETPI.sh#L580

https Only enabled for Stretch+
- https://github.com/Fourdee/DietPi/blob/master/PREP_SYSTEM_FOR_DIETPI.sh#L865-L870

Image contains http.
- meveric-all meveric-jessie are https

**Comment by Fourdee** [comment]
> & DietPi upgrades to Stretch

Ah yes, I see. 

```DISTRO_TARGET=stretch```, and ```G_DISTRO=$DISTRO_TARGET G_DISTRO_NAME="$DISTRO_TARGET_NAME" G_HW_MODEL=$G_HW_MODEL G_RUN_CMD /DietPi/dietpi/func/dietpi-set_software apt-mirror 'default'``` before pre-req packages are installed ```apt-transport-https```?

**Comment by Fourdee** [comment]
Pre-req ```apt-transport-https``` at start of script should fix it, requires testing to confirm:
https://github.com/Fourdee/DietPi/commit/d5dca2512d98412a66892585e582cd9e51b0776b

Dev branch PREP with updated code:
```
wget https://raw.githubusercontent.com/Fourdee/DietPi/dev/PREP_SYSTEM_FOR_DIETPI.sh -O PREP_SYSTEM_FOR_DIETPI.sh
chmod +x PREP_SYSTEM_FOR_DIETPI.sh
./PREP_SYSTEM_FOR_DIETPI.sh
```

@optio50 
Any chance you would be willing to re-try PREP on  https://oph.mdrjr.net/meveric/images/Jessie/Debian-Jessie-1.1-20170515-U.img.xz using the above updated code and see if issue is resolved?

**Comment by optio50** [comment]
Fresh install

Fails at Step 5

DietPi-PREP: G_AGI: apt-transport-https apt-utils bash-completion bc bzip2                                                                                        
│ ca-certificates console-setup cron curl debconf dirmngr ethtool fake-hwclock gnupg                                                                                
│ htop iputils-ping isc-dhcp-client kmod locales nano p7zip-full parted psmisc                                                                                      
│ resolvconf sudo systemd-sysv tzdata udev unzip usbutils wget whiptail crda
| firmware-atheros firmware-brcm80211 firmware-iwlwifi iw rfkill wireless-tools                                                                                     
│ wpasupplicant firmware-ralink dropbear initramfs-tools dosfstools hdparm                                                                                          
│  - Exit code: 100                                                                                                                                                 
│  - DietPi version: v6.16.0 (Fourdee/master) | HW_MODEL:13 | HW_ARCH:2 | DISTRO:4                                                                                  
│  - Image creator: n/a                                                                                                                                             
│  - Pre-image: n/a                                                                                                                                                 
│                                                                                                                                                                   
│ Log file contents:                                                                                                                                                
│ E: Method https has died unexpectedly!                                                                                                                            
│ E: Sub-process https received a segmentation fault.                                                                                                               
│ E: Method /usr/lib/apt/methods/https did not start correctly 

I logged in a separate console and disabled https in /etc/apt/sources.list and hit retry.

It continues for a few more min and then again

DietPi-Set_Hardware: G_AGI: alsa-utils                                                                                                                            
│  - Exit code: 100                                                                                                                                                 
│  - DietPi version: v6.17.0 (Fourdee/master) | HW_MODEL:13 | HW_ARCH:2 | DISTRO:4                                                                                  
│  - Image creator: n/a                                                                                                                                             
│  - Pre-image: n/a                                                                                                                                                 
│                                                                                                                                                                   
│ Log file contents:                                                                                                                                                
│ E: Method https has died unexpectedly!                                                                                                                            
│ E: Sub-process https received a segmentation fault.                                                                                                               
│ E: Method /usr/lib/apt/methods/https did not start correctly                                                                                                      
│                                                                                                                                                                   
│                                                                                                                                                                   
│                                                                                                                                                                   
│ Unable to continue, DietPi-Set_Hardware will now terminate.    

https was reenabled so I then again disable https in /etc/apt/sources.list and hit retry. 

Script completes at this point.

reboot
first login

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
-bash: [: missing `]'
-bash: [: missing `]'
-bash: [: missing `]'
-bash: [: missing `]'

apt update

Get:1 http://fuzon.co.uk/meveric all InRelease [15.2 kB]
Get:2 http://fuzon.co.uk/meveric jessie InRelease [5630 B]
Get:3 http://fuzon.co.uk/meveric all/main armhf Packages [39.4 kB]
Get:4 http://fuzon.co.uk/meveric all/testing armhf Packages [7420 B]
Get:5 http://fuzon.co.uk/meveric all/u armhf Packages [3891 B]
Get:6 http://fuzon.co.uk/meveric jessie/main armhf Packages [78.5 kB]
Get:7 http://fuzon.co.uk/meveric jessie/backports armhf Packages [85.8 kB]
0% [Working]

https was reenabled so I then again disable https in /etc/apt/sources.list 

apt update completes correctly

reboot

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
-bash: [: missing `]'
-bash: [: missing `]'
-bash: [: missing `]'
-bash: [: missing `]'

**Comment by optio50** [comment]
Well after several more attempts I still cant get the revised PREP_SYSTEM_FOR_DIETPI.sh
So I locked down the  sources.list with chattr +i and it completed successfully. However, still has erros and the banner never comes up.

So I left the chattr +i in place  and retried with the original published git PREP_SYSTEM_FOR_DIETPI.sh
Complet successfully rebooted proceded with minimal install and all seems to be ok. Currently install additional software. Well see how it goes (also removing the chattr +i now)

**Comment by optio50** [comment]
May or may not be related to previous issue with https.
Pi-Hole install


[FAILED] '/etc/init.d/pihole-FTL' does not exist or cannot be written to by current user.                            │                                                           
│                                                                                                                                                                               
│ Please verify the existance of the file, retry with proper permissions or apply the setting manually:                │                                                           
│         # Required-Stop: $network $remote_fs

**Comment by MichaIng** [comment]
@optio50 
This means Pi-hole did not install successfully, right? Otherwise the file would be in place. Looks like the installer failed.
I guess it should, if APT fails, as it also does+requires some APT package installs. But to verify that, we would require install log. Pi-hole should show about what failed an what succeeded.

**Comment by optio50** [comment]
its gotta be https related.
owncloud fails too
 INFO ] DietPi-Software | G_THREAD_WAIT_0 | wget https://download.owncloud.org/community/owncloud-latest.zip -O 47.zip
[ INFO ] DietPi-Software | G_THREAD_WAIT_0 | wget https://download.owncloud.org/community/owncloud-latest.zip -O 47.zip
[ INFO ] DietPi-Software | G_THREAD_WAIT_0 | wget https://download.owncloud.org/community/owncloud-latest.zip -O 47.zip
[ INFO ] DietPi-Software | G_THREAD_WAIT_0 | wget https://download.owncloud.org/community/owncloud-latest.zip -O 47.zip
[ INFO ] DietPi-Software | G_THREAD_WAIT_0 | wget https://download.owncloud.org/community/owncloud-latest.zip -O 47.zip
[ INFO ] DietPi-Software | G_THREAD_WAIT_0 | wget https://download.owncloud.org/community/owncloud-latest.zip -O 47.zip
[ INFO ] DietPi-Software | G_THREAD_WAIT_0 | wget https://download.owncloud.org/community/owncloud-latest.zip -O 47.zip
[ INFO ] DietPi-Software | G_THREAD_WAIT_0 | wget https://download.owncloud.org/community/owncloud-latest.zip -O 47.zip
[ INFO ] DietPi-Software | G_THREAD_WAIT_0 | wget https://download.owncloud.org/community/owncloud-latest.zip -O 47.zip
[ INFO ] DietPi-Software | G_THREAD_WAIT_0 | wget https://download.owncloud.org/community/owncloud-latest.zip -O 47.zip
[ INFO ] DietPi-Software | G_THREAD_WAIT_0 | wget https://download.owncloud.org/community/owncloud-latest.zip -O 47.zip
[ INFO ] DietPi-Software | G_THREAD_WAIT_0 | wget https://download.owncloud.org/community/owncloud-latest.zip -O 47.zip
[ INFO ] DietPi-Software | G_THREAD_WAIT_0 | wget https://download.owncloud.org/community/owncloud-latest.zip -O 47.zip
[ INFO ] DietPi-Software | G_THREAD_WAIT_0 | wget https://download.owncloud.org/community/owncloud-latest.zip -O 47.zip
[ INFO ] DietPi-Software | G_THREAD_WAIT_0 | wget https://download.owncloud.org/community/owncloud-latest.zip -O 47.zip

**Comment by MichaIng** [comment]
@optio50 
Seems to be.

The part before this messages is the interesting one, the ones you posted are expected, depending on how much time the APT install (attempt) took.

As said I faced this error once and it required a special solution. Have to do some research to find the needed hints/remember what it was.

Can you please paste content of all your source files:
```
cat /etc/apt/sources.list
cat /etc/apt/sources.list.d/*
```

**Comment by optio50** [comment]
I lost heart in the process. I installed Ubuntu Mate 16.04 on the Odroid U3 and then installed Pi-Hole.
I only have one emmc for the U3 and I just got the Ubuntu Mate 16.04 running pretty good.
I can dig up a microsd and do some more testing this week if you want to pursue this.

**Comment by MichaIng** [comment]
@optio50 
I understand. 

Did more research and indeed the error often appears due to faulty packages. So either apt-transport-https or the apt package itself seem to be faulty.

Solution could be to switch to http:// sources and reinstall both packages: 
apt install --reinstall apt apt-transport-https

Others also reported that it could only be fixed by purging the pachage(s) first and do a fresh install.
But the error might be in the base image already. To test, before running DietPi-PREP,  install the https package, switch and test https deb sources.

But this is something we can test, if @Fourdee has an U3 there?

**Comment by Fourdee** [comment]
@MichaIng 

>  @Fourdee has an U3 there?

Nope ☹️. Although, could try replicating on XU4 jessie image, will have a stab when I get some time.

**Comment by MichaIng** [comment]
Will mark as closed due to general cleanup. Feel free to reopen if issue persists with current version.
