### ISSUE TITLE
DietPi Image | ASUS Tinker Board

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#806]
> http://dietpi.com/phpbb/viewtopic.php?f=9&t=1218&p=5846&hilit=ASUS+tinker#p5175

Funding required for board purchase:
![image](https://cloud.githubusercontent.com/assets/7077026/23833805/ba03f448-0742-11e7-9703-a7eb2a357cce.png)

**Comment by Fourdee** [comment]
Funded by donation (Thanks Ioan!):
On order, awaiting arrival.

**Comment by Fourdee** [comment]
Arrived, time to crack on 😃

**Comment by Fourdee** [comment]
Notes:

- WifI ```8723bs```
- Xorg: ```/etc/X11/xorg.conf.d/20-modesetting.conf```
```
Section "Device"
    Identifier  "Rockchip Graphics"
    Driver      "modesetting"
    Option      "AccelMethod"    "glamor"
    Option      "DRI"            "2"
EndSection
```
```
ii  libva-rockchip1:armhf                0.13-2                                    armhf        The VA-API library for the Rock-Chips RK3288.
#libmali-rk*
```
- Alsa:
- 3.5mm = ```hw:0,2```
- hdmi = ```hw:1,0```
```
**** List of PLAYBACK Hardware Devices ****
card 0: Audio [USB Audio], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: Audio [USB Audio], device 1: USB Audio [USB Audio #1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: Audio [USB Audio], device 2: USB Audio [USB Audio #2]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: rockchipminiarm [rockchip,miniarm-codec], device 0: ff890000.i2s-i2s-hifi i2s-hifi-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```
- Apt:
```/etc/apt/sources.list.d/linaro-overlay-repo.list```
```
deb http://repo.linaro.org/ubuntu/linaro-overlay jessie main
```
``` /etc/apt/sources.list.d/testing.list ```
```
deb     http://cdn.debian.net/debian/    testing main contrib non-free
deb     http://security.debian.org/         testing/updates  main contrib non-free
```

**Comment by Fourdee** [comment]
Performance:
- HDMI Limited to 1080p. Not native 4K.
- Network throughput
```
Client connecting to 192.168.0.112, TCP port 5001
TCP window size: 91.9 KByte (default)
------------------------------------------------------------
[  5] local 192.168.0.25 port 42764 connected with 192.168.0.112 port 5001
[  4] local 192.168.0.25 port 5001 connected with 192.168.0.112 port 49883
[ ID] Interval       Transfer     Bandwidth
[  5]  0.0-30.0 sec  1.49 GBytes   427 Mbits/sec
[  4]  0.0-30.0 sec  3.05 GBytes   873 Mbits/sec

#2
Client connecting to 192.168.0.112, TCP port 5001
TCP window size:  127 KByte (default)
------------------------------------------------------------
[  5] local 192.168.0.25 port 42766 connected with 192.168.0.112 port 5001
[  4] local 192.168.0.25 port 5001 connected with 192.168.0.112 port 49884
[ ID] Interval       Transfer     Bandwidth
[  5]  0.0-30.0 sec  1.74 GBytes   498 Mbits/sec
[  4]  0.0-30.0 sec  3.01 GBytes   861 Mbits/sec

```
- Heat eff 70'c 1 min burn
- SD IO, Sandisk Extreme ```Flash Storage : Write = 37.9 MB/s | Read = 56.2 MB/s```
- Dual channel DDR3 is awesome: ```RAM           : Write = 541 MB/s | Read = 714 MB/s```
- WiFi range/strength is poor with onboard antenna: ``` Signal level=-76 dBm```

**Comment by Fourdee** [comment]
GPU:
Not available via optional linaro/testing repos.
```
root@DietPi:~# apt-cache search libva-rockchip1
root@DietPi:~# apt-cache search libmali-rk
```

https://github.com/rockchip-linux/libvdpau-rockchip/blob/master/debian/control

Packages available on Official image ```/packages```

Regardless, official image v1.4 GPU is buggy for me. Desktop loads, 5 seconds later black screen and no signal reported on HDMI output. No issues in ```/var/log/Xorg*```.

We'll disable GPU for the time being, wait for improved drivers from Asus/RK.

**Comment by Fourdee** [comment]
GPS installed by default on official image... interesting
![image](https://cloud.githubusercontent.com/assets/7077026/24105471/e24c13d2-0d7c-11e7-99a5-4daca592910b.png)

```
dpkg -l | grep gpsd
ii  gpsd                      3.16-1~bpo8+1               armhf        Global Positioning System - daemon
```

**Comment by Fourdee** [comment]
Completed:
http://dietpi.com/#download

**Comment by Invictaz** [comment]
Well done. Impressive how fast you did it. Was it because the official blob for the GPU and the CPU distro already available from Rockchip?

**Comment by Fourdee** [comment]
@Invictaz 

Thanks 👍 We actually used the official ASUS v1.4 image, stripped it (and then some) then optimized for DietPi.

Once we had the info on WiFi/BT modules and various other things, DietPi is coded to allow for new boards fairly quickly. Just a case of adding new code and done.

Just bear in mind, GPU features are not support yet in DietPi for this image, due to:
https://github.com/Fourdee/DietPi/issues/806#issuecomment-287760711

**Comment by mmagnetix** [comment]
@Fourdee 👍 

receiving the board this week. how does the sdcard perform? the controller is UHS-I might speed things up?

Regards,
Magnetix

**Comment by Invictaz** [comment]
@Fourdee 

Still too bad there is no Allwinner A10 build. I really could use it. 
Some people said that the libvdpau and GPU support is now there partially. 

See also my links on issue #824

**Comment by Fourdee** [comment]
> receiving the board this week. how does the sdcard perform? the controller is UHS-I might speed things up?

@mmagnetix 
Oh yes it does, SDIO 3.0 is really nice, Sandisk Extreme 32GB 60MB/s write rated
![image](https://cloud.githubusercontent.com/assets/7077026/24199292/e94e9a6c-0f00-11e7-9ea5-69ac766c5523.png)

May get better performance on higher speed card, although, I doubt it will touch Odroid's EMMC 150MB/s

**Comment by mmagnetix** [comment]
@Fourdee 

Awesome. The goal of Asus is almost there (to be a Raspberry PI killer) Hopefully the GPU driver issue is corrected in the next couple of days. Then Odroid C2 has competition. 
 
the heatsink in the package is it enough to keep the CPU <85c or is did the CPU throttle kicked in?

**Comment by Fourdee** [comment]
@mmagnetix 

> Hopefully the GPU driver issue is corrected in the next couple of days.

Yep, hopefully. I will test the board on another monitor, just incase its an EDID/auto detect issue.

> the heatsink in the package is it enough to keep the CPU <85c or is did the CPU throttle kicked in?

Seems fine, I did a quick 1min CPU burn (8 threads) and only reached 70'c. So in terms of real-world server usage, should never hit thermal throttling unless at full load for 10+ mins.

>  Then Odroid C2 has competition.

For me, the C2 is still a much better board. Especially for Kodi usage:
- C2: 4K resolution
- Asus: 1080p resolution (not 4K)
- C2: 990MB/s network bandwidth
- Asus: 500MB/s network bandwidth (in send direction i believe): https://github.com/Fourdee/DietPi/issues/806#issuecomment-287755120
- C2: 150MB/s R/W with EMMC module
- C2: Cheaper
- C2: Available hi-end audio DAC HATS (HiFi Shield)
- C2: Better comminuty and support by Odroid

Asus doesn't even have an official forum for the tinkerboard (that Google can find). There is no comminuty.

Hopefully things will improve, Asus have the global resources and funds. Lets wait and see :)

**Comment by Fourdee** [comment]
Official v1.4 Asus TB image:

- 🈺 Interesting, on another TV, i still get the same screen blank after 5 seconds in desktop, however, it does return signal after another 5 seconds.
- 🈺 Chromium + Youtube performance under ```egl``` is dreadful, 720p@30fps = 5-10fps
- 🈺 Kodi Playback (Bunny 1080p@60fps) is jittery, possible vsync issue (tearing), 100% CPU usage @ 1.5GHz

Yep, think we'll have to wait for improved driver from Asus/Rk on this one. Not worth the current experience.

**Comment by mmagnetix** [comment]
Looks like a hdmi resolution mode issueDid you tried all resolutions to check if it stablized on say 720p.Op 23 mrt. 2017 14:24 schreef Dan <notifications@github.com>:Interesting, on another TV, i still get the same screen blank after 5 seconds in desktop, however, it does return signal after another 5 seconds.
Chromium + Youtube performance is dreadful, 720p@30fps = 5-10fps

**Comment by mmagnetix** [comment]
I heard some rumors that the Tinker Board works OK (desktop/Kodi) with mainline Kernel 4.11.

**Comment by Fourdee** [comment]
#### Recreate image with latest kernel (based on official v1.8 beta image):
- 🈯️ http://dietpi.com/downloads/images/DietPi_AsusTinkerBoard-armv7-(Jessie).7z
- Debian Stretch
- test updated GPU drivers


--- 

#### Known issues
- NTPD may fail to update in time on first run.

**Comment by bpatrik** [comment]
Is there any update on this?
v1.8 stable and v1.9 beta is out since may:
https://www.asus.com/us/Single-Board-Computer/Tinker-Board/HelpDesk_Download/

**Comment by bpatrik** [comment]
I found a strange bug with Dietpi, Tiner os (1.8 stable, 19, beta) but not with armbian.
If I server some files over http, the tcp connection stops sometimes and the files won't get transferred.
I've also reported this error here too, with more details:
https://tinkerboarding.co.uk/forum/thread-493.html

p.s.: after trying out most of the OS for tinker board, this is my favorite so far. Great job! :)

**Comment by Fourdee** [comment]
Image updated (based on TinkerOS 2.0.1 beta): 
http://dietpi.com/downloads/images/DietPi_AsusTinkerBoard-armv7-(Stretch).7z

**Comment by qu-crypt** [comment]
do you have any update on this? Is there any hope that the GPU issue is going to be fixed?

**Comment by adamotte** [comment]
Can you update the image based on lastest version v2.0.7 - Debian stretch based. 2018/06/22 ?
Thanks.

**Comment by Fourdee** [comment]
@adamotte 

Hi thanks for the request, the current DietPi image uses 2.0.5. I'll flag this for update.

**Comment by adamotte** [comment]
@Fourdee, Simple question : Does DietPi support the S version (so with the eMMC) or do we need to install it on SD card ?

**Comment by Fourdee** [comment]
@adamotte 

Yes it supports S version 👍 

Marking as closed in favor of:
https://github.com/Fourdee/DietPi/issues/2026

**Comment by Fourdee** [comment]
@adamotte 

TinkerOS 2.0.7:
https://dietpi.com/downloads/testing/DietPi_ASUSTB-ARMv7-Stretch.7z

Although, this release breaks WiFi. Will leave under testing.
https://github.com/Fourdee/DietPi/issues/2026#issuecomment-414431922

**Comment by adamotte** [comment]
Hum i still need WiFi (remote work :beach_umbrella: :tropical_drink: :sun_with_face:) so i will wait before upgrade. Anyway thanks for the update.

**Comment by ravaz** [comment]
The test link for v2.0.7 doens't work anymore. It there any update on this topic?

**Comment by Fourdee** [comment]
@ravaz 

2.0.7 image on its way, see https://github.com/Fourdee/DietPi/issues/2070 for link when its completed.

**Comment by MichaIng** [comment]
@Fourdee 
Just found: https://tinkerboarding.co.uk/forum/thread-69.html

Beneath DietPi is listed with the still correct note that GPU features are disabled. But since this is not a note on the official TinkerOS, perhaps something has changed there or it does work on fresh TinkerOS and we break something with DietPi preparation, perhaps accidentally auto purge some required firmware package?

**Comment by Fourdee** [comment]
@MichaIng 

> break something with DietPi preparation, perhaps accidentally auto purge some required firmware package?

Possibly. I also believe the install has a custom version of xserver packages, to support the GPU. However, I was unsuccessful in getting the provided packages to work, after PREP.

When i'am able, i'll take another look. But low priority for the moment due to other tickets.
